//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenJob.Course.DbCourse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom_Student
    {
        public int IdCombination { get; set; }
        public int IdClassRoom { get; set; }
        public int IdStudent { get; set; }
        public int IdLesson { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
