//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenJob.Course.DbCourse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRoom_Student
    {
        public int IdCombination { get; set; }
        public int IdClassRoom { get; set; }
        public int IdStudent { get; set; }
        public int IdLesson { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
    }
}
