//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenJob.Course.DbCourse.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogDefinition
    {
        public System.Guid UidLog { get; set; }
        public string LogAction { get; set; }
        public string LogSeverity { get; set; }
        public string LogMessage { get; set; }
    }
}
